In [1]:

import pandas as pd
from debugpy.common.util import force_ascii
from matplotlib.font_manager import json_load
import json
from Jumpit_Crawling_Functions import *
from Data_Analysis import *

In [2]:
mergeData = pd.read_json('../Data_Files/Crawling_DataFile_MergePage_json_20250512.txt')

In [3]:
mergeDataTrans = mergeData.T
mergeDataTrans

,title,company,pride,mainWork,requirements,preferential,welfare,procedures,education,closedAt,jobCategory,techStack,minCareer,maxCareer,jobLocation,date
49210,데이터 분석 플랫폼 개발자경력 610년,엠로,[2호선 역세권 기업],"[데이터 분석 플랫폼 백엔드 및 프론트엔드 개발, Java, Python 기반의 데...","[학사 졸업4년제 이상, Java, JavaScript, Spring Framewo...","[대용량 데이터 처리 및 분산 처리 경험Hadoop, Spark 등, Dataiku...","[2회 성과급 지급PI, 출퇴근 교통비 지원법인카드 사용, 중식대 월 20만원 제공...",[서류검토 1차 면접 2차 면접 채용검진 처우 협의 최종 합격],대학교졸업4년 이상,2025년 05월 18일,"웹 풀스택 개발자,SW솔루션","[Java, Spring Framework, JavaScript, Python]",6,10,[서울 영등포구],2025년05월12일
49577,머신러닝 엔지니어 시니어,심플랫폼,[],"[산업용 ML 모델 개발 및 최적화, 산업용 시계열 및 비전 데이터진동, 온도, 압...","[데이터 과학 혹은 소프트웨어 공학 전공인 분, 머신 러닝 및 소프트웨어 공학 총 ...","[Kubernetes 기반 ML 서비스 운영 경험이 있으면 좋아요 Docker, H...","[4대 사회보험 가입, 주5일 근무, 법정퇴직금, 경조휴가 및 경조금 지급, 매월 ...",[서류 전형 코딩테스트SW엔지니어링+데이터분석 기술 면접 임원 면접 처우협의...,대학교졸업4년 이상,2025년 05월 22일,인공지능머신러닝,"[Python, PyTorch, TensorFlow, DVC, Docker, Hel...",6,15,[서울 금천구],2025년05월12일
49678,서버개발팀 모바일 개발자경력,사이버다임,"[2호선 역세권 기업, #유연근무제, #도서구입비지원]","[자사 솔루션 모바일 개발, Destiny ECM데스티니 ECM은 고객사 인프라 환...","[관련 경력을 5년 이상 보유한 분, React Native 개발이 가능한 분, N...","[채팅 클라이언트 개발 경험이 있으신 분, 기업용 솔루션 개발 경험이 있으신 분, ...","[직원 중심의 조직문화를 만들어갑니다, 유연근무제와 자유로운 연차 사용으로 일과 삶...",[서류전형 1차 면접 2차 면접 필요 시 입사 협의],대학졸업2년 이상,2025년 05월 24일,"iOS 개발자,안드로이드 개발자","[Android Studio, Nodejs, Webpack, Redux, React...",5,15,[서울 송파구],2025년05월12일
49027,백엔드 개발자 채용 5년 이상,싸이터,[],"[선박 사이버보안 소프트웨어 백엔드 개발, API 서버 기능 개발]","[학력 학력무관, 개발 경력 5년 이상12년 이하, Springboot 개발, K...","[MSA 기반 개발 경험, AWS 기반 개발 경험, Reactjs 개발 경험, 대용...","[연구 및 자기계발을 위한 컨퍼런스세미나교육 지원 및 도서 제공, 대학원 석박사 과...",[서류전형 1차면접직무 2차면접임원 대표이사면접 최종합격],무관,2025년 05월 13일,서버백엔드 개발자,"[Spring Boot, Kubernetes, MySQL, Kafka, Elasti...",5,12,[서울 금천구],2025년05월12일
49281,신입 개발자 채용,하이퍼에픽,"[9호선 역세권 기업, 코퍼스코리아 계열사]","[어플리케이션 백엔드 서버 개발 및 유지보수, 관련 부서와 긴밀하게 협업하면서 서비...","[spring boot, kotlin 경험이 있는 분, postgresql 사용 경...","[type script 경험이 있는 분, nodejs 경험이 있는 분]","[퇴직금, 4대보험, 간식 제공, 자율 복장, 수평적 조직 문화 회식 강요 X]","[근무환경, 고용형태 정규직, 근무지역 서울 강남구, 급여조건 협의 된 연봉 ...",무관,2025년 05월 16일,"서버백엔드 개발자,웹 풀스택 개발자","[Spring Boot, Kotlin, PostgreSQL, Git, TypeScr...",0,2,[서울 강남구],2025년05월12일
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50728,QA 테스터 모집3년5년계약직,위버스브레인,"[위버스마인드 계열사, 2호선 역세권 기업, #자유복장, #맛있는간식냠냠]","[자사 서비스의 기획, 개발 과정의 테스트 케이스 작성 및 실행, 개별 프로젝트에 ...","[모바일 앱 및 웹 서비스 QA 경력 35년, 앱 서비스 운영 과정에서 QA를 경험...","[개발 프로세스에 대한 이해가 있으신 분, 구축 및 운영 프로젝트 참여 경력이 있으...","[중식제공 구디역 최고 맛집 구내식당 중식 제공, 야근 시 석식 제공, 보험 4...","[채용절차 서류전형 면접전형 최종합격, 채용형태 정규직 수습기간 3개월, 급...",대학교졸업4년 이상,2025년 06월 10일,QA 엔지니어,[QA],3,5,[서울 구로구],2025년05월12일
50725,백엔드개발자 모집11년15년,위버스브레인,"[위버스마인드 계열사, 2호선 역세권 기업, #자유복장, #맛있는간식냠냠]","[프로젝트 설계, AI 기반 교육 어프리케이션의 API 개발, 코드 품질 관리]","[1115년 경력언어, 프레임워크 무관, Python 기반 웹 어플리케이션 서버 개...","[컨테이너 기반으로 어플리케이션 배포 및 운영 경험, 클린 코드 및 클린 아키텍처에...","[중식제공 구디역 최고 맛집 구내식당 중식 제공, 야근 시 석식 제공, 보험 4...","[채용절차 서류전형 면접전형 최종합격, 채용형태 정규직 수습기간 3개월, 급...",무관,2025년 06월 10일,서버백엔드 개발자,"[PHP, Git, Python, REST API, AI인공지능]",11,15,[서울 구로구],2025년05월12일
50765,홈페이지 및 IT 관리,이디앤씨,[2호선 역세권 기업],"[IT 인프라 전산 자산 관리PC 및 서버, 네트워크 하드웨어 등, 네트워크 및 정...","[학력 무관 유관 경력 2년 이상, 네트워크 및 서버 또는 리눅스 자격증 필수,...","[커뮤니케이션 우수자, 워드프레스와 같은 CMS 개발 또는 운영 경험]","[연금보험 국민연금 , 고용보험, 산재보험, 건강보험, 상해보험, 휴무휴가행사 주5...",[자신의 경력을 증명할 수 있는 추가 자료가 있으면 필히 제출 부탁드립니다 특히 진...,무관,2025년 06월 14일,웹 풀스택 개발자,"[JavaScript, Linux, HTML5, CSS 3]",2,12,[서울 영등포구],2025년05월12일
50773,전산 담당자 계약직 채용46년,얼라인드제네틱스,"[4호선 역세권 기업, #전공우대, #유연근무제]","[내부 인트라넷ERPGW 유지 관리, 파일 서버시놀로지 Nas 등 유지 관리, 정보...","[근무형태 계약직정규직 전환가능, 경력 4년6년, 학력 전산 관련 전공자 전문...","[전산 직무 근무 경험, 제조업 ERP 운영 경험, 전산 회계 가능자, 운전 가능자]",[장기근속자 포상제도 안식월 휴가 5년 단위 10일 유급휴가 + 기본급 50 상여...,"[1차, 2차 면접은 서류전형 합격자에 한하여 개별통보상황에 따라 2차 면접은 생략...",대학졸업2년 이상,2025년 06월 10일,"기술지원,정보보안 담당자","[ERP, SW]",4,6,[경기 안양시],2025년05월12일
50772,전산 담당자 계약직 채용13년,얼라인드제네틱스,"[4호선 역세권 기업, #전공우대, #유연근무제]","[내부 인트라넷ERPGW 유지 관리, 파일 서버시놀로지 Nas 등 유지 관리, 정보...","[근무형태 계약직정규직 전환가능, 경력 1년3년, 학력 전산 관련 전공자 전문...","[전산 직무 근무 경험, 제조업 ERP 운영 경험, 전산 회계 가능자, 운전 가능자]",[장기근속자 포상제도 안식월 휴가 5년 단위 10일 유급휴가 + 기본급 50 상여...,"[1차, 2차 면접은 서류전형 합격자에 한하여 개별통보상황에 따라 2차 면접은 생략...",대학졸업2년 이상,2025년 06월 10일,"기술지원,정보보안 담당자","[ERP, SW]",1,3,[경기 안양시],2025년05월12일

In [4]:
# jobCategory의 리스트 값들을 원핫인코딩 해서 mergeDataTrans 칼럼에 넣는 방식

jobCategory = mergeDataTrans['jobCategory'].apply(lambda x : x.split(','))
jobCategory = jobCategory.explode()
jobCategory = pd.get_dummies(jobCategory)

In [5]:
jobCategory

,DBA,HW임베디드,QA 엔지니어,SW솔루션,VRAR3D,devops시스템 엔지니어,iOS 개발자,개발 PM,게임 서버 개발자,게임 클라이언트 개발자,...,블록체인,빅데이터 엔지니어,서버백엔드 개발자,안드로이드 개발자,웹 풀스택 개발자,웹퍼블리셔,인공지능머신러닝,정보보안 담당자,크로스플랫폼 앱개발자,프론트엔드 개발자
49210,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
49210,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49577,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
49678,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49678,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50765,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
50773,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
50773,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
50772,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
50772,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [6]:
education = mergeDataTrans['education']
education

49210    대학교졸업4년 이상
49577    대학교졸업4년 이상
49678     대학졸업2년 이상
49027            무관
49281            무관
            ...
50728    대학교졸업4년 이상
50725            무관
50765            무관
50773     대학졸업2년 이상
50772     대학졸업2년 이상
Name: education, Length: 1405, dtype: object

In [7]:
educationJobCategory = combineDataFrames(jobCategory, education)
educationJobCategory

,education,DBA,HW임베디드,QA 엔지니어,SW솔루션,VRAR3D,devops시스템 엔지니어,iOS 개발자,개발 PM,게임 서버 개발자,...,블록체인,빅데이터 엔지니어,서버백엔드 개발자,안드로이드 개발자,웹 풀스택 개발자,웹퍼블리셔,인공지능머신러닝,정보보안 담당자,크로스플랫폼 앱개발자,프론트엔드 개발자
49210,대학교졸업4년 이상,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
49210,대학교졸업4년 이상,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49577,대학교졸업4년 이상,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
49678,대학졸업2년 이상,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
49678,대학졸업2년 이상,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50765,무관,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
50773,대학졸업2년 이상,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
50773,대학졸업2년 이상,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
50772,대학졸업2년 이상,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
50772,대학졸업2년 이상,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [8]:
#education별로 jobCategory들의 개수 세기
educationJobCategory = educationJobCategory.groupby('education').sum()
educationJobCategory

,DBA,HW임베디드,QA 엔지니어,SW솔루션,VRAR3D,devops시스템 엔지니어,iOS 개발자,개발 PM,게임 서버 개발자,게임 클라이언트 개발자,...,블록체인,빅데이터 엔지니어,서버백엔드 개발자,안드로이드 개발자,웹 풀스택 개발자,웹퍼블리셔,인공지능머신러닝,정보보안 담당자,크로스플랫폼 앱개발자,프론트엔드 개발자
education,,,,,,,,,,,,,,,,,,,,,
고등학교졸업 이상,1,15,1,19,0,5,3,7,0,1,...,0,1,28,1,5,0,1,1,7,4
고등학교졸업 이상졸업예정자 가능,0,0,0,3,0,1,1,0,0,0,...,0,0,0,0,0,0,1,0,0,1
대학교졸업4년 이상,5,96,13,159,4,48,6,24,1,5,...,5,24,106,15,37,7,66,20,8,38
대학교졸업4년 이상졸업예정자 가능,1,4,2,19,1,4,1,0,0,0,...,0,3,5,1,0,0,16,0,3,4
"대학졸업2,3년 이상졸업예정자 가능",0,2,2,6,0,4,0,0,1,1,...,1,2,2,0,4,0,1,0,0,1
대학졸업2년 이상,7,31,3,73,2,12,5,10,0,0,...,0,9,35,5,20,0,13,7,1,18
무관,10,20,13,66,0,38,14,31,6,10,...,10,14,152,20,24,0,39,12,15,68
박사졸업,0,0,0,2,0,0,0,0,0,0,...,1,0,0,0,0,0,2,0,0,0
석사졸업 이상,0,3,1,2,1,0,0,2,0,0,...,1,2,7,0,0,0,28,0,0,0
석사졸업 이상졸업예정자 가능,0,2,1,4,1,1,0,0,0,0,...,0,0,0,0,0,0,6,1,0,0

In [10]:
json = educationJobCategory.to_json(force_ascii=False)
to_data_file(json)

AttributeError: 'dict' object has no attribute 'to_json'

In [ ]:
dataCleaned = data.drop(columns=['title_y','companyName','techStack_x','jobLocation_y','date_y','career'],
          axis=1, inplace=False)

In [ ]:
dataCleaned.rename({'title_x': 'title', 'jobLocation_x': 'jobLocation','techStack_y':'techStack'},
                   axis=1, inplace=True)
dataRenamed = dataCleaned.rename(
    {
        'title':'제목',
        'company' : '회사명',
        'pride' : '특이사항',
        'mainWork' : '주요업무',
        'requirements' : '자격요건',
        'preferential' : '우대사항',
        'welfare' : '복지 및 혜a택',
        'procedures' : '채용 절차',
        'date_x' : '공고일',
        'jobCategory' : '직무',
        'minCareer' : '최소 경력',
        'maxCareer' : '최대 경력',
        'techStack' : '기술 스택'
    }
    ,inplace=False
)

dataRenamed.info()

In [ ]:
dataCleaned

In [ ]:
categoryEducation = data[['title_x', 'jobCategory', 'education']]

In [ ]:
categoryEducation = categoryEducation.rename(
    columns={'title_x': 'title', 'jobCategory': 'category', 'education': 'education'})
categoryEducation = categoryEducation.drop_duplicates(subset=['title', 'category', 'education'], keep='first')
categoryEducation = categoryEducation.reset_index(drop=True)
categoryEducation = categoryEducation.dropna()

In [ ]:
categoryEducation['category'].info()

In [ ]:
categoryEducation.category.value_counts()

In [ ]:
techStackList = data['techStack_x'].to_list()
techStackList
techStacks = sum(techStackList,[])
techStacks

In [ ]:
data2 = pd.DataFrame(techStacks)
data2.value_counts()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm
import matplotlib as mpl
from matplotlib import rc

# 한글 폰트 설정
# font_path = 'C:/Windows/Fonts/malgun.ttf'  # Windows의 경우
# font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'  # Linux의 경우
#font_path = 'System/Library/Fonts/AppleGothic.ttf'  # Mac의 경우
#font_prop = fm.FontProperties(fname=font_path, size=12)
#mpl.rc('font', family=font_prop.get_name())
#mpl.rcParams['axes.unicode_minus'] = False  # 마이너스 기호 깨짐 방지
rc('font', family='AppleGothic')  ## 이 두 줄을
plt.rcParams['axes.unicode_minus'] = False  ## 추가해줍니다. 

# 그래프 크기 설정
plt.figure(figsize=(10, 6))

# 그래프 스타일 설정
sns.set_style("whitegrid")

# 그래프 그리기
sns.barplot(x=techStackTop10['TechStack'], y=techStackTop10['Count'], palette='viridis')
plt.title('Top 10 Tech Stacks', fontsize=16, fontproperties=font_prop)
plt.xlabel('Tech Stack', fontsize=14, fontproperties=font_prop)
plt.ylabel('Count', fontsize=14, fontproperties=font_prop)
plt.xticks(rotation=45, fontsize=12, fontproperties=font_prop)
plt.yticks(fontsize=12, fontproperties=font_prop)
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl

# 그래프 크기 설정
plt.figure(figsize=(10, 6))

# 그래프 스타일 설정
sns.set_style("whitegrid")

# 그래프 그리기
# (여기서는 techStackTop10 DataFrame이 정의되어 있다고 가정합니다.)
sns.barplot(x=techStackTop10['TechStack'], y=techStackTop10['Count'], palette='viridis')
plt.title('Top 10 Tech Stacks', fontsize=16)
plt.xlabel('Tech Stack', fontsize=14)
plt.ylabel('Count', fontsize=14)
plt.xticks(rotation=45, fontsize=12)
plt.yticks(fontsize=12)
plt.show()

In [ ]:
# techStack 안의 리스트를 전부 분해해서 새로운 행으로 만들기
data0504Exploded = data0504.explode('techStack')
data0504Exploded.reset_index(drop=True, inplace=True)
data0504Exploded

In [ ]:
techCareerData = data0504Exploded[['minCareer', 'techStack']]

In [ ]:
techStackTop10List = techStackTop10['TechStack'].tolist()
techStackTop10List

In [ ]:
top10Data = techCareerData[techCareerData['techStack'].isin(techStackTop10List)].copy()
top10Data

In [ ]:
top10Data.index = top10Data['techStack']
top10Data = top10Data.drop(columns=['techStack'])

In [ ]:
# 테크 스택별로 보통 몇년의 경력을 요구하는지 보여주는 그래프 생성
plt.figure(figsize=(12, 8))
sns.set_style("whitegrid")
# viridis 말고 다른 팔레트도 사용해보세요. 예: 'coolwarm', 'plasma', 'magma', 'cividis'
sns.barplot(x=top10Data.index, y=top10Data['minCareer'], palette='plasma')
plt.title('Minimum Career Requirement by Tech Stack', fontsize=16, fontproperties=font_prop)
plt.xlabel('Tech Stack', fontsize=14, fontproperties=font_prop)
plt.ylabel('Minimum Career (Years)', fontsize=14, fontproperties=font_prop)
plt.xticks(rotation=45, fontsize=12, fontproperties=font_prop)
plt.yticks(fontsize=12, fontproperties=font_prop)
plt.show()

In [ ]:
# 탑 10 기술스택 별로 평균 계산

techStackTop10Avg = top10Data.groupby('techStack')['minCareer'].mean().reset_index()
techStackTop10Avg.columns = ['TechStack', 'AvgMinCareer']
techStackTop10Avg = techStackTop10Avg.sort_values(by='AvgMinCareer', ascending=False)
techStackTop10Avg

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl

# mac 한글 폰트 설정
font_path = '/Library/Fonts/Arial Unicode.ttf'  # Mac 시스템 기본 고딕 폰트 경로
font_prop = fm.FontProperties(fname=font_path, size=12)
mpl.rc('font', family=font_prop.get_name())
mpl.rcParams['axes.unicode_minus'] = False  # 마이너스 기호 깨짐 방지

# 그래프 크기 설정

plt.figure(figsize=(12, 8))

sns.set_style("whitegrid")
# viridis 말고 다른 팔레트도 사용해보세요. 예: 'coolwarm', 'plasma', 'magma', 'cividis'
sns.barplot(x=techStackTop10Avg['AvgMinCareer'], y=techStackTop10Avg['TechStack'], palette='coolwarm', ci=None)
plt.title('기술 스택별 요구되는 평균 경럭', fontsize=16, fontproperties=font_prop)
plt.xlabel('평균 경력 (년)', fontsize=14, fontproperties=font_prop)
plt.ylabel('기술 스택', fontsize=14, fontproperties=font_prop)
plt.xticks(rotation=0, fontsize=12)
plt.yticks(fontsize=12)
plt.show()

In [ ]:
data_detail

In [ ]:
import pandas as pd
dataYesterday = pd.read_json('../Data_Files/Crawling_DataFile_DetailPage_json_20250510.txt')
dataToday = pd.read_json('../Data_Files/Crawling_DataFile_DetailPage_json_20250511.txt')

In [ ]:
dataYesterday

In [ ]:
dataToday

In [ ]:
dataNew = dataToday[~dataToday.index.isin(dataYesterday.index)]

In [ ]:
dataNew

In [ ]:
dataClosed = dataYesterday[~dataYesterday.index.isin(dataToday.index)]

In [ ]:
dataClosed = getClosedPost(dataYesterday, dataToday)
dataClosed

In [ ]:
# 특정 techStack의 지역별 분포

stackLocation = dataToday[['techStack', 'jobLocation']]
stackLocation

In [ ]:
stackLocation = stackLocation.explode('techStack')
stackLocation